pull_request_rules:
  - name: Automatic Depfu merging
    conditions:
      - author=depfu[bot]
      - approved-reviews-by=Favna
      - base=main
      - label~=^Meta:\ Dependencies
    actions:
      merge:
        method: squash
