version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

aliases:
  - &checkout
    checkout
  - &store_artifacts
    store_artifacts:
      path: coverage
  - &codecov
    codecov/upload:
      file: coverage/*.json

job_node_10: &job_node_10
  docker:
    - image: circleci/node:10

job_node_11: &job_node_11
  docker:
    - image: circleci/node:11

job_node_12: &job_node_12
  docker:
    - image: circleci/node:12

run_yarn: &run_yarn
  name: Install yarn packages
  command: yarn install

save_yarn: &save_yarn
  save_cache:
    name: Save Yarn Package Cache
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - node_modules

restore_yarn: &restore_yarn
  restore_cache:
    name: Restore Yarn Package Cache
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

commands:
  nodejs:
    description: Primary flow
    steps:
    - *checkout
    - <<: *restore_yarn
    - run:
        <<: *run_yarn
    - <<: *save_yarn
    - run:
        name: Lint all libraries
        command: yarn lint
    - run:
        name: Test all libraries
        command: yarn ci:test
    - *store_artifacts
    - *codecov

# List of jobs
jobs:
  node-v10:
    <<: *job_node_10
    steps:
      - nodejs
  node-v11:
    <<: *job_node_11
    steps:
      - nodejs
  node-v12:
    <<: *job_node_12
    steps:
      - nodejs

workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v10
      - node-v11
      - node-v12

  nightly:
    jobs:
      - node-v10
      - node-v11
      - node-v12
    triggers:
      - schedule:
          cron: 0 2 * * *
          filters:
            branches:
              only:
                - master