version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

aliases:
  - &restore_yarn_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - yarn-packages-{{ arch }}-{{ .Branch }}-
        - yarn-packages-{{ arch }}-
  - &run_yarn
    run:
      name: Install Packages
      command: yarn --frozen-lockfile
  - &store_artifacts
    store_artifacts:
      path: '**/coverage'
  - &codecov
    codecov/upload:
      file: '**/coverage/*.json'
  - &checkout
    checkout

commands:
  nodejs:
    description: Main NodeJS flow
    steps:
      - *checkout
      - *restore_yarn_cache
      - *run_yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Lint all libraries
          command: yarn lint
      - run:
          name: Test all libraries
          command: yarn test:coverage
      - run:
          name: Build packages
          command: yarn build
      - *store_artifacts
      - *codecov

# List of jobs
jobs:
  node-v10:
    docker:
      - image: circleci/node:10
    steps:
      - nodejs
  node-v11:
    docker:
      - image: circleci/node:11
    steps:
      - nodejs
  node-v12:
    docker:
      - image: circleci/node:12
    steps:
      - nodejs

workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v10
      - node-v11
      - node-v12

  every-sunday-at-night:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - node-v10
      - node-v11
      - node-v12