name: Unit Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  test:
    name: Node v${{ matrix.node_version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12, 13]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Cache node modules
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          ${{ matrix.os }}-yarn-${{ env.cache-name }}-
          ${{ matrix.os }}-yarn-
          ${{ matrix.os }}-

    - name: Install Deps
      run: yarn
    - name: Build Project
      run: yarn build
    - name: Test
      run: yarn test