name: Update API Docs

on:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  UpdateDocs:
    name: Update API Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Restore CI Cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-10-${{ hashFiles('**/yarn.lock') }}
    - name: Install Deps
      run: yarn
    - name: Generate docs
      run: yarn docs
    - name: Commit any changes
      run: |
        GITHUB_REPO_URL="https://${GITHUB_ACTOR}:${{ secrets.PUSH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git";
        git config --local user.email "favwarebot@gmail.com";
        git config --local user.name "Favware-bot";
        git commit -nsam "docs(api): update API docs";
        git push "${GITHUB_REPO_URL}" HEAD:master;
